### PR TITLE
Cleanup & IMPROVE mAP +0.1% !!!

### PR DESCRIPTION
**Pull request by developer0hye**
# Original version
yolov3 tiny voc
AP for aeroplane = 0.7445
AP for bicycle = 0.8010
AP for bird = 0.6944
AP for boat = 0.6162
AP for bottle = 0.5641
AP for bus = 0.7888
AP for car = 0.8225
AP for cat = 0.7794
AP for chair = 0.5475
AP for cow = 0.7662
AP for diningtable = 0.6554
AP for dog = 0.7303
AP for horse = 0.7880
AP for motorbike = 0.8114
AP for person = 0.7820
AP for pottedplant = 0.4380
AP for sheep = 0.7135
AP for sofa = 0.6836
AP for train = 0.7983
AP for tvmonitor = 0.7302
Mean AP = 0.7128

# This Modified Version

AP for aeroplane = 0.7479
AP for bicycle = 0.8012
AP for bird = 0.6936
AP for boat = 0.6154
AP for bottle = 0.5640
AP for bus = 0.7900
AP for car = 0.8230
AP for cat = 0.7842
AP for chair = 0.5478
AP for cow = 0.7675
AP for diningtable = 0.6597
AP for dog = 0.7297
AP for horse = 0.7885
AP for motorbike = 0.8131
AP for person = 0.7825
AP for pottedplant = 0.4372
AP for sheep = 0.7142
AP for sofa = 0.6847
AP for train = 0.7995
AP for tvmonitor = 0.7301
Mean AP = 0.7137

**71.28% VS 71.37%**

yolov3, yolov2 and yolov2tiny may get improvements if we modified theses codes like yolov3tiny.

### CODE REVIEW

**Comment by yjh0410** [comment]
Great ！！

**Comment by yjh0410** [comment]
Sorry, my tiny-yolo-v3 only got a worse result 19.6 mAP.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 晚上9:25
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yjh0410/pytorch-yolo-v2-v3] Cleanup &amp; IMPROVE mAP +0.1% !!! (#22)




original version
 yolov3 tiny voc
 AP for aeroplane = 0.7445
 AP for bicycle = 0.8010
 AP for bird = 0.6944
 AP for boat = 0.6162
 AP for bottle = 0.5641
 AP for bus = 0.7888
 AP for car = 0.8225
 AP for cat = 0.7794
 AP for chair = 0.5475
 AP for cow = 0.7662
 AP for diningtable = 0.6554
 AP for dog = 0.7303
 AP for horse = 0.7880
 AP for motorbike = 0.8114
 AP for person = 0.7820
 AP for pottedplant = 0.4380
 AP for sheep = 0.7135
 AP for sofa = 0.6836
 AP for train = 0.7983
 AP for tvmonitor = 0.7302
 Mean AP = 0.7128
 
This Modified Version
 
AP for aeroplane = 0.7479
 AP for bicycle = 0.8012
 AP for bird = 0.6936
 AP for boat = 0.6154
 AP for bottle = 0.5640
 AP for bus = 0.7900
 AP for car = 0.8230
 AP for cat = 0.7842
 AP for chair = 0.5478
 AP for cow = 0.7675
 AP for diningtable = 0.6597
 AP for dog = 0.7297
 AP for horse = 0.7885
 AP for motorbike = 0.8131
 AP for person = 0.7825
 AP for pottedplant = 0.4372
 AP for sheep = 0.7142
 AP for sofa = 0.6847
 AP for train = 0.7995
 AP for tvmonitor = 0.7301
 Mean AP = 0.7137
 
71.28% VS 71.37
 
yolov3, yolov2 and yolov2tiny may get improvements if we modified theses codes like yolov3tiny.
 
 
You can view, comment on, or merge this pull request online at:
 
&nbsp; https://github.com/yjh0410/pytorch-yolo-v2-v3/pull/22
 
Commit Summary
    
Cleanup &amp; IMPROVE mAP +0.1% !!!
  
File Changes
    
     M     models/tiny_yolo_v3.py     (188)   
  
Patch Links:
    
https://github.com/yjh0410/pytorch-yolo-v2-v3/pull/22.patch
   
https://github.com/yjh0410/pytorch-yolo-v2-v3/pull/22.diff

**Comment by yjh0410** [comment]
When I use&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 晚上9:25
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yjh0410/pytorch-yolo-v2-v3] Cleanup &amp; IMPROVE mAP +0.1% !!! (#22)




original version
 yolov3 tiny voc
 AP for aeroplane = 0.7445
 AP for bicycle = 0.8010
 AP for bird = 0.6944
 AP for boat = 0.6162
 AP for bottle = 0.5641
 AP for bus = 0.7888
 AP for car = 0.8225
 AP for cat = 0.7794
 AP for chair = 0.5475
 AP for cow = 0.7662
 AP for diningtable = 0.6554
 AP for dog = 0.7303
 AP for horse = 0.7880
 AP for motorbike = 0.8114
 AP for person = 0.7820
 AP for pottedplant = 0.4380
 AP for sheep = 0.7135
 AP for sofa = 0.6836
 AP for train = 0.7983
 AP for tvmonitor = 0.7302
 Mean AP = 0.7128
 
This Modified Version
 
AP for aeroplane = 0.7479
 AP for bicycle = 0.8012
 AP for bird = 0.6936
 AP for boat = 0.6154
 AP for bottle = 0.5640
 AP for bus = 0.7900
 AP for car = 0.8230
 AP for cat = 0.7842
 AP for chair = 0.5478
 AP for cow = 0.7675
 AP for diningtable = 0.6597
 AP for dog = 0.7297
 AP for horse = 0.7885
 AP for motorbike = 0.8131
 AP for person = 0.7825
 AP for pottedplant = 0.4372
 AP for sheep = 0.7142
 AP for sofa = 0.6847
 AP for train = 0.7995
 AP for tvmonitor = 0.7301
 Mean AP = 0.7137
 
71.28% VS 71.37
 
yolov3, yolov2 and yolov2tiny may get improvements if we modified theses codes like yolov3tiny.
 
 
You can view, comment on, or merge this pull request online at:
 
&nbsp; https://github.com/yjh0410/pytorch-yolo-v2-v3/pull/22
 
Commit Summary
    
Cleanup &amp; IMPROVE mAP +0.1% !!!
  
File Changes
    
     M     models/tiny_yolo_v3.py     (188)   
  
Patch Links:
    
https://github.com/yjh0410/pytorch-yolo-v2-v3/pull/22.patch
   
https://github.com/yjh0410/pytorch-yolo-v2-v3/pull/22.diff

**Comment by developer0hye** [comment]
@yjh0410 

Really?!

**Comment by yjh0410** [comment]
When I run the code on cuda:0, everything is OK. But I run the code on cuda:1, I got 19 mAP. I'm trying to find the bug.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 晚上10:44
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Cleanup &amp; IMPROVE mAP +0.1% !!! (#22)





 
@yjh0410
 
Really?!

**Comment by developer0hye** [comment]
OMG!

hmm... I never use the multi GPU, so I am hard to guess the reason!

**Comment by developer0hye** [comment]
@yjh0410 
Could you merge the last PR and test again?

**Comment by yjh0410** [comment]
Oh, yeah !! It works !!
But there is one line code need to be modified：
self.scale_torch&nbsp;=&nbsp;torch.tensor(self.scale.copy(),&nbsp;device=device).float()

otherwise it will bring a error about multi-gpus.


The detector also run a little faster !! Amazing !
I learn much from your modified codes.
Thanks a lot !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 晚上10:55
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Cleanup &amp; IMPROVE mAP +0.1% !!! (#22)





 
@yjh0410
 Could you merge the last PR and test again?

**Comment by developer0hye** [comment]
@yjh0410 
Got it! We did it!

**Comment by developer0hye** [comment]
@yjh0410 
Do you have a plan to update the modified code about self.scale_torch??
or do you wait my PR?

**Comment by yjh0410** [comment]
I plan to modifed all models including yolo-v2, v3, tiny-yolo-v2 based on your the last PR. And I will update the whole project tomorrow.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 晚上11:17
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Cleanup &amp; IMPROVE mAP +0.1% !!! (#22)





 
@yjh0410
 Do you have a plan to update the modified code about self.scale_torch??
 or do you wait for my PR?

**Comment by developer0hye** [comment]
@yjh0410 
Ah! Okay! Cheer up! I am happy to meet you! Keep up the good work together~

**Comment by yjh0410** [comment]
I'm glad to meet you, too! You really helped me a lot！Very grateful ！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 晚上11:22
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Cleanup &amp; IMPROVE mAP +0.1% !!! (#22)





 
@yjh0410
 Ah! Okay! Cheer up! I am happy to meet you! Keep up the good work together~

**Comment by yjh0410** [comment]
I'm sorry to tell you that there is no improvement on my device(AMD R5 3600 cpu &amp; GTX-1660ti gpu), even slower:
tiny-yolo-v3 : 0.035ms vs 0.033ms
yolo-v2 : 0.023ms vs 0.017ms


But mAP didn't change.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yonghye Kwon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 晚上11:22
收件人:&nbsp;"yjh0410/pytorch-yolo-v2-v3"<pytorch-yolo-v2-v3@noreply.github.com&gt;;
抄送:&nbsp;"ら ．Secret"<1394571815@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [yjh0410/pytorch-yolo-v2-v3] Cleanup &amp; IMPROVE mAP +0.1% !!! (#22)





 
@yjh0410
 Ah! Okay! Cheer up! I am happy to meet you! Keep up the good work together~

**Comment by developer0hye** [comment]
@yjh0410 
Ah, really... Okay, but I will try to improve mAP!

**Pull request merged**
